-- Fix ammo table numeric precision
ALTER TABLE ammo ALTER COLUMN speed TYPE NUMERIC(8,2);
ALTER TABLE ammo ALTER COLUMN penetration TYPE NUMERIC(8,2);
ALTER TABLE ammo ALTER COLUMN damage_factor TYPE NUMERIC(8,2);
ALTER TABLE ammo ALTER COLUMN sail_damage TYPE NUMERIC(8,2);
ALTER TABLE ammo ALTER COLUMN crew_damage TYPE NUMERIC(8,2);
ALTER TABLE ammo ALTER COLUMN min_damage TYPE NUMERIC(8,2);
ALTER TABLE ammo ALTER COLUMN mass TYPE NUMERIC(8,2);
ALTER TABLE ammo ALTER COLUMN radius TYPE NUMERIC(8,2);
ALTER TABLE ammo ALTER COLUMN reload_factor TYPE NUMERIC(8,2);
ALTER TABLE ammo ALTER COLUMN distance_factor TYPE NUMERIC(8,2);
